language: objective-c
osx_image: xcode9.3

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=SwiftyMessenger.xcworkspace
  - FRAMEWORK_SCHEME="SwiftyMessenger"
  - SDK=iphonesimulator11.3
  - RUN_TESTS="YES"
  - POD_LINT="NO"
  matrix:
    - DESTINATION="OS=11.3,name=iPhone X"
    - DESTINATION="OS=10.3.1,name=iPhone 6"
    - DESTINATION="OS=9.3,name=iPhone 5s"

before_install:
- rm -rf /Users/travis/Library/Developer/Xcode/DerivedData/SwiftyMessenger-*/
- rvm use $RVM_RUBY_VERSION

install:
- bundle install

script: 
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

# Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$FRAMEWORK_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$FRAMEWORK_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=YES build | xcpretty;
    fi

after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f test/xml_report/cobertura.xml -X coveragepy -X gcov -X xcode